server:
  port: 10081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_register_and_config_center?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: flms04